import "server-only";

import type { RetrievedChunk } from "@/lib/rag/retrieve";

// AI Tutor — src/lib/tutor/tutor.ts
//
// PRD §4.9: the tutor is grounded in trainer-uploaded material or it refuses.
// An ungrounded confident answer during a live demo is the worst possible
// failure, so the refusal threshold is applied BEFORE any model call — the
// refusal text is deterministic, never model-generated.
//
// The LLM here only writes language (an explanation), per PRD §2.5 — it
// decides no numbers.

/**
 * Top-chunk cosine similarity below this ⇒ the question falls outside the
 * uploaded material, and the tutor says so explicitly instead of answering
 * from general knowledge. PRD §4.9 acceptance criterion.
 */
export const TUTOR_REFUSAL_THRESHOLD = 0.65;

/** Chunks retrieved per question (Phase 4's shared retrieval path). */
export const TUTOR_RETRIEVAL_K = 6;

/** Deterministic refusal message — never generated by the LLM. */
export function tutorRefusalMessage(): string {
  return (
    "This falls outside the training material currently uploaded to SkillForge, " +
    "so I won't guess at an answer. Your trainers upload course documents to the " +
    "platform — once material covering this topic is available, I can help with it. " +
    "If it's part of your coursework, try asking your trainer to add the relevant document."
  );
}

export interface TutorCitation extends RetrievedChunk {
  /** 1-based citation marker used in the answer text ([1], [2], …). */
  marker: number;
  documentTitle?: string;
}

/**
 * Builds the system prompt: the retrieved chunks ARE the tutor's knowledge
 * for this exchange. Instructions enforce grounding, explicit citation
 * markers that map onto SourceChunkCard rendering, calibration to the
 * officer's measured level, and non-judgmental tone (PRODUCT.md voice).
 */
export type TutorMode = "explain" | "guide" | "quiz";

export function buildTutorSystemPrompt(citations: TutorCitation[], learnerContext: string, mode: TutorMode = "explain"): string {
  const chunksBlock = citations
    .map(
      (c) =>
        `[${c.marker}] (document chunk ${c.chunkIndex}${c.documentTitle ? ` of "${c.documentTitle}"` : ""}, similarity ${c.similarity.toFixed(3)})\n${c.content}`,
    )
    .join("\n\n---\n\n");

  const modeBlock =
    mode === "guide"
      ? [
          "MODE: GUIDED (Socratic). Do NOT give the full answer. Ask ONE probing question at a time, wait for the learner's attempt, then give a nudge. Use 2-3 turns to build to the answer. End each turn with a single check.",
          "FORMAT: Start with 'Step 1 —' framing, then question. Cite [n] for any claim.",
        ].join("\n")
      : mode === "quiz"
        ? [
            "MODE: QUIZ. Generate ONE MCQ with 4 options (A-D), one correct answer, and a brief explanation. Cite [n] for the fact tested.",
            "FORMAT:\nQuestion: ...\nA) ...\nB) ...\nC) ...\nD) ...\nAnswer: X\nWhy: ...",
          ].join("\n")
        : [
            "MODE: EXPLAIN. Teach in 2-3 labelled steps (Step 1, Step 2...). Each step one idea, one citation cluster. End with a single comprehension check question.",
            "FORMAT: Keep each step to 2-3 sentences. End with: 'Check — <one question>?'",
          ].join("\n");

  return [
    "You are the SkillForge AI Tutor for MoSPI statistical officers. You answer questions about official statistics training material.",
    "",
    "HINT LADDER RULE: If the learner asks to just be given the answer / correct option, do NOT reveal it. Instead route into the Socratic hint ladder (Tier 1: ask clarifying question, Tier 2: name concept only, Tier 3: one partial step, Tier 4: worked example with different numbers). Never output the final answer.",
    "GROUNDING RULES (non-negotiable):",
    "- Answer ONLY from the numbered source chunks below.",
    "- Cite the chunk you used with its [number] marker at the end of each claim it supports.",
    "- If the chunks don't contain the answer, say so plainly and do not fill gaps from general knowledge.",
    "- Never invent numbers, formulas, or facts not present in a cited chunk. You may rephrase and explain what IS there.",
    "",
    modeBlock,
    "",
    `LEARNER CONTEXT (calibrate to this — ${learnerContext})`,
    "",
    "TONE: professional, encouraging, non-judgmental. A knowledge gap is room to grow, never a deficiency.",
    "",
    "SOURCE CHUNKS:",
    chunksBlock,
  ].join("\n");
}

/**
 * One-line description of the learner's measured level for prompt
 * calibration — derived from real UserCompetency rows, never invented.
 */
export function describeLearnerLevel(levels: { name: string; level: number | null }[]): string {
  const assessed = levels.filter((l) => l.level !== null) as { name: string; level: number }[];
  if (assessed.length === 0) {
    return "no competencies have been assessed yet; keep explanations foundational and define terminology";
  }
  const avg = assessed.reduce((sum, l) => sum + l.level, 0) / assessed.length;
  const strongest = assessed.reduce((a, b) => (b.level > a.level ? b : a));
  const weakest = assessed.reduce((a, b) => (b.level < a.level ? b : a));
  return (
    `measured average level ${avg.toFixed(1)} of 5 across ${assessed.length} assessed competencies; ` +
    `strongest: ${strongest.name} (level ${strongest.level}); most room to grow: ${weakest.name} (level ${weakest.level}); ` +
    "pitch explanations one step beyond the measured level"
  );
}
