import "server-only";

import type { RetrievedChunk } from "@/lib/rag/retrieve";

// AI Tutor — src/lib/tutor/tutor.ts
//
// Retrieval always runs first, and its similarity — not the model — decides
// whether an answer is grounded, blended or general (see TutorBasis). The UI
// labels each, so general knowledge is never passed off as sourced. Off-topic
// questions are declined with deterministic text, never model-generated.
//
// The LLM here only writes language (an explanation), per PRD §2.5 — it
// decides no numbers.

/**
 * Top-chunk cosine similarity below this ⇒ no retrieved passage is relevant
 * enough to cite. The quiz refuses below it; the tutor falls back to a
 * clearly labelled general explanation for in-scope questions.
 */
export const TUTOR_REFUSAL_THRESHOLD = 0.65;

/** Chunks retrieved per question (Phase 4's shared retrieval path). */
export const TUTOR_RETRIEVAL_K = 6;

export type TutorLanguage = "en" | "hi";

/** Appended to tutor/quiz prompts. Citations, math and technical terms stay intact. */
export function languageInstruction(language: TutorLanguage): string {
  return language === "hi"
    ? "LANGUAGE: Respond entirely in Hindi (Devanagari script), in clear formal Hindi suitable for government officers. Keep citation markers like [1], math notation, and standard statistical terms (e.g. CPI, GDP, SQL) as they are; you may add the English term in brackets after a Hindi term the first time it appears."
    : "LANGUAGE: Respond in English.";
}

/** Deterministic refusal message — never generated by the LLM. */
export function tutorRefusalMessage(language: TutorLanguage = "en"): string {
  if (language === "hi") {
    return (
      "यह प्रश्न ट्यूटर के दायरे से बाहर है। ट्यूटर केवल आपके पाठ्यक्रम और दक्षता क्षेत्रों — सांख्यिकी, डेटा, डिजिटल गवर्नेंस " +
      "और व्यावसायिक कौशल — से जुड़े प्रश्नों में सहायता करता है।"
    );
  }
  return (
    "That's outside what the tutor covers. It helps with your coursework and competency areas — " +
    "statistics, data and technology, digital governance, and professional skills."
  );
}

/**
 * Top-chunk similarity at or above this ⇒ the learner's material covers the
 * question well enough to answer from it alone.
 */
export const TUTOR_STRONG_MATCH = 0.75;

/**
 * Where an answer's content comes from, decided deterministically from
 * retrieval similarity before any model call:
 * - material: the retrieved passages cover it; answer only from them.
 * - blended:  passages partly cover it; cite them, and put anything beyond
 *             them under a labelled "Beyond your material" section.
 * - general:  nothing relevant was retrieved; an on-topic question gets a
 *             clearly labelled general explanation with no citations.
 */
export type TutorBasis = "material" | "blended" | "general";

export function tutorBasis(topSimilarity: number | null): TutorBasis {
  if (topSimilarity !== null && topSimilarity >= TUTOR_STRONG_MATCH) return "material";
  if (topSimilarity !== null && topSimilarity >= TUTOR_REFUSAL_THRESHOLD) return "blended";
  return "general";
}

/**
 * The model's only way to decline: reply with exactly this token. The route
 * swaps it for the deterministic refusal message, so refusal wording is
 * never model-generated.
 */
export const OUT_OF_SCOPE_SENTINEL = "[[OUT_OF_SCOPE]]";

/** Cheap pre-check for obvious chit-chat, so it never costs a model call. */
export function isGenericOffTopic(question: string): boolean {
  const q = question.toLowerCase();
  const patterns = [
    /\bwhat('s| is) the time\b/,
    /\bwhat time is it\b/,
    /\bwho is (ronaldo|messi|virat kohli|shah rukh khan|taylor swift)\b/,
    /\bpicasso\b/,
    /\bcelebrity\b/,
    /\bweather\b/,
    /\btell me a joke\b/,
    /\b(movie|film|song) recommendations?\b/,
  ];
  return patterns.some((re) => re.test(q));
}

export interface TutorCitation extends RetrievedChunk {
  /** 1-based citation marker used in the answer text ([1], [2], …). */
  marker: number;
  documentTitle?: string;
}

export type TutorMode = "explain" | "guide" | "quiz";

const SCOPE_BLOCK = [
  "SCOPE (decide this first):",
  "- IN SCOPE: anything a MoSPI / Indian Statistical Service officer would study for work — statistics and probability, survey design and sampling, official statistics (NSO/NSSO, census, national accounts, price, labour, agricultural and industrial statistics), economics, data analysis and data science, Python/R/SQL/Excel for data work, data quality and management, digital governance, data protection (e.g. DPDPA), public administration, and professional or behavioural skills (communication, leadership, ethics). Also anything the learner's material covers.",
  "- OUT OF SCOPE: current events and news, sport, entertainment, celebrities, weather, jokes, personal, medical, legal or financial advice, party politics, and anything unrelated to professional learning.",
  `- If the question is OUT OF SCOPE, reply with exactly ${OUT_OF_SCOPE_SENTINEL} and nothing else. Otherwise, answer it properly — never refuse an in-scope question.`,
].join("\n");

function basisBlock(basis: TutorBasis): string {
  if (basis === "material") {
    return [
      "GROUNDING (the learner's material covers this):",
      "- Answer from the numbered source chunks below, citing the chunk behind each claim with its [n] marker at the end of the sentence.",
      "- Never invent numbers, formulas or facts that are not in a chunk. You may rephrase and explain what is there.",
    ].join("\n");
  }
  if (basis === "blended") {
    return [
      "GROUNDING (the learner's material only partly covers this):",
      "- Use the numbered source chunks below first, citing each claim you take from them with its [n] marker.",
      "- Where the chunks don't cover part of the question, complete the answer from established, textbook-standard knowledge — but put ALL of that under a final heading exactly `## Beyond your material`, with no [n] markers in that section.",
      "- Never attribute general knowledge to a chunk. Never invent specific figures (e.g. a current index value or survey round result); say it isn't available instead.",
    ].join("\n");
  }
  return [
    "GROUNDING (nothing in the learner's material covers this):",
    "- Answer from established, textbook-standard knowledge. Do not use [n] citation markers — there are no sources.",
    "- Stick to standard definitions, methods and formulas. Never invent specific figures (e.g. a current index value or survey round result); say it isn't available instead.",
  ].join("\n");
}

function modeBlock(mode: TutorMode): string {
  if (mode === "guide") {
    return [
      "MODE: GUIDED (Socratic). Do not give the full answer. Ask ONE probing question at a time, respond to the learner's attempt with a nudge, and build to the answer over 2–3 turns.",
      "HINT LADDER: if the learner asks to just be told the answer, step through hints instead — Tier 1 a clarifying question, Tier 2 name the concept, Tier 3 one partial step, Tier 4 a worked example with different numbers.",
    ].join("\n");
  }
  if (mode === "quiz") {
    return [
      "MODE: QUIZ. Write EXACTLY ONE multiple-choice question, once.",
      "FORMAT (strict):\nQuestion: ...\nA) ...\nB) ...\nC) ...\nD) ...\nAnswer: X\nWhy: ... (2–3 sentences)",
    ].join("\n");
  }
  return [
    "MODE: EXPLAIN.",
    "- Answer the actual question directly in the first one or two sentences — no preamble.",
    "- Then build understanding in 2–4 short, labelled steps (e.g. `**Step 1 — …**`), one idea each. Use a small worked example, formula or table where it helps.",
    "- Match depth to what was asked: a definition question gets a tight answer; a 'teach me' request gets the full build-up.",
    "- End with one line: `Check — <one short question>?`",
  ].join("\n");
}

/**
 * Builds the system prompt. The basis (decided by retrieval similarity, not
 * by the model) sets how strictly the answer is tied to the learner's
 * material; the scope block lets the model decline off-topic questions only
 * via the sentinel.
 */
export function buildTutorSystemPrompt(
  citations: TutorCitation[],
  learnerContext: string,
  mode: TutorMode = "explain",
  language: TutorLanguage = "en",
  basis: TutorBasis = "material",
): string {
  const chunksBlock = citations
    .map(
      (c) =>
        `[${c.marker}] (document chunk ${c.chunkIndex}${c.documentTitle ? ` of "${c.documentTitle}"` : ""}, similarity ${c.similarity.toFixed(3)})\n${c.content}`,
    )
    .join("\n\n---\n\n");

  return [
    "You are the SkillForge AI Tutor for officers of India's Ministry of Statistics and Programme Implementation (MoSPI). You teach clearly and precisely, like an experienced NSSTA faculty member.",
    "",
    SCOPE_BLOCK,
    "",
    basisBlock(basis),
    "",
    modeBlock(mode),
    "",
    "OUTPUT FORMAT: Markdown — short paragraphs, bold for key terms, bullet lists, tables where they help. No top-level # heading.",
    "MATH: Use $...$ inline and $$...$$ for display math, with properly escaped LaTeX (e.g. $S_h$, $\\sum_{h} W_h S_h$, $n_h$). Never emit bare LaTeX commands outside math delimiters; write $i$-th, not $i$th.",
    "",
    `LEARNER CONTEXT (calibrate depth to this — ${learnerContext})`,
    "TONE: professional, encouraging, non-judgmental. A knowledge gap is room to grow, never a deficiency.",
    languageInstruction(language),
    ...(citations.length ? ["", "SOURCE CHUNKS:", chunksBlock] : []),
  ].join("\n");
}

/**
 * One-line description of the learner's measured level for prompt
 * calibration — derived from real UserCompetency rows, never invented.
 */
export function describeLearnerLevel(levels: { name: string; level: number | null }[]): string {
  const assessed = levels.filter((l) => l.level !== null) as { name: string; level: number }[];
  if (assessed.length === 0) {
    return "no competencies have been assessed yet; keep explanations foundational and define terminology";
  }
  const avg = assessed.reduce((sum, l) => sum + l.level, 0) / assessed.length;
  const strongest = assessed.reduce((a, b) => (b.level > a.level ? b : a));
  const weakest = assessed.reduce((a, b) => (b.level < a.level ? b : a));
  return (
    `measured average level ${avg.toFixed(1)} of 5 across ${assessed.length} assessed competencies; ` +
    `strongest: ${strongest.name} (level ${strongest.level}); most room to grow: ${weakest.name} (level ${weakest.level}); ` +
    "pitch explanations one step beyond the measured level"
  );
}
